name: Upload yo pypi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: compiling
          run "python .\setup.py sdist bdist_wheel
          run echo "hola"
